services:
  postgres:
    image: postgres:15
    container_name: guinni-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guinni_db}
      POSTGRES_USER: ${POSTGRES_USER:-guinni_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guinni_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-guinni_user} -d ${POSTGRES_DB:-guinni_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: